<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    myPromise.catch(error => {
    // do something with the error.
    });
    error is the argument passed in to the reject method.


    Note: the then and catch methods can be chained to the promise declaration if you choose.

    then 和 catch可以链式调用

    <script>
        const makeServerRequest = new Promise((resolve, reject) => {
            // responseFromServer is set to false to represent an unsuccessful response from a server
            let responseFromServer = false;

            if (responseFromServer) {
                resolve("We got the data");
            } else {
                reject("Data not received");
            }
        });

        makeServerRequest.then(result => {
            console.log(result);
        }).catch(error => {
            console.log(error);
        });
    </script>
</body>

</html>